# Generated by Django 5.0.7 on 2025-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCodeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_username', models.CharField(max_length=100)),
                ('entered_code', models.CharField(max_length=12)),
                ('matched_username', models.CharField(max_length=100)),
                ('matched_user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
