# Generated by Django 5.0.7 on 2025-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usercodematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercodematch',
            name='matched_user_full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usercodematch',
            name='matched_user_profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
